"""schema iniziale

Revision ID: ba8fc983f7f3
Revises: 
Create Date: 2026-08-22 18:37:31.943677
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ba8fc983f7f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_verificata_il', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utente_email'), 'utente', ['email'], unique=True)
    op.create_table('sessione',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scade_il', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessione_utente_id'), 'sessione', ['utente_id'], unique=False)
    op.create_table('evento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('tema', sa.String(length=40), nullable=False),
    sa.Column('stato', sa.String(length=20), nullable=False),
    sa.Column('titolo_interno', sa.String(length=160), nullable=False),
    sa.Column('proprietario_utente_id', sa.UUID(), nullable=True),
    sa.Column('proprietario_sessione_id', sa.UUID(), nullable=True),
    sa.Column('versione', sa.BigInteger(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('aggiornato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proprietario_utente_id IS NOT NULL OR proprietario_sessione_id IS NOT NULL', name='evento_ha_un_proprietario'),
    sa.ForeignKeyConstraint(['proprietario_sessione_id'], ['sessione.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proprietario_utente_id'], ['utente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evento_sessione', 'evento', ['proprietario_sessione_id'], unique=False)
    op.create_index('ix_evento_utente', 'evento', ['proprietario_utente_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('chiave_storage', sa.String(length=255), nullable=False),
    sa.Column('larghezza', sa.Integer(), nullable=True),
    sa.Column('altezza', sa.Integer(), nullable=True),
    sa.Column('byte', sa.Integer(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_evento_id'), 'asset', ['evento_id'], unique=False)
    op.create_table('blocco',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('posizione', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('contenuto', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blocco_evento_pos', 'blocco', ['evento_id', 'posizione'], unique=False)
    op.create_table('diritto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent')
    )
    op.create_index(op.f('ix_diritto_evento_id'), 'diritto', ['evento_id'], unique=False)
    op.create_table('link_condivisione',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('scade_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocato_il', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_condivisione_evento_id'), 'link_condivisione', ['evento_id'], unique=False)
    op.create_index(op.f('ix_link_condivisione_token'), 'link_condivisione', ['token'], unique=True)
    op.create_table('rsvp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('referente', sa.String(length=160), nullable=False),
    sa.Column('ospiti', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('messaggio', sa.Text(), nullable=False),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['link_id'], ['link_condivisione.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvp_evento_id'), 'rsvp', ['evento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rsvp_evento_id'), table_name='rsvp')
    op.drop_table('rsvp')
    op.drop_index(op.f('ix_link_condivisione_token'), table_name='link_condivisione')
    op.drop_index(op.f('ix_link_condivisione_evento_id'), table_name='link_condivisione')
    op.drop_table('link_condivisione')
    op.drop_index(op.f('ix_diritto_evento_id'), table_name='diritto')
    op.drop_table('diritto')
    op.drop_index('ix_blocco_evento_pos', table_name='blocco')
    op.drop_table('blocco')
    op.drop_index(op.f('ix_asset_evento_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index('ix_evento_utente', table_name='evento')
    op.drop_index('ix_evento_sessione', table_name='evento')
    op.drop_table('evento')
    op.drop_index(op.f('ix_sessione_utente_id'), table_name='sessione')
    op.drop_table('sessione')
    op.drop_index(op.f('ix_utente_email'), table_name='utente')
    op.drop_table('utente')
    # ### end Alembic commands ###
